#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pandoc
Version  : 2.17.1.1
Release  : 33
URL      : https://github.com/jgm/pandoc/releases/download/2.17.1.1/pandoc-2.17.1.1-linux-amd64.tar.gz
Source0  : https://github.com/jgm/pandoc/releases/download/2.17.1.1/pandoc-2.17.1.1-linux-amd64.tar.gz
Source1  : https://github.com/jgm/pandoc/archive/2.17.1.1/sources-2.17.1.1.tar.gz
Summary  : The universal markup converter
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0 MIT WTFPL
Requires: pandoc-bin = %{version}-%{release}
Requires: pandoc-license = %{version}-%{release}
Requires: pandoc-man = %{version}-%{release}

%description
Pandoc is a Haskell library for converting from one markup format to another,
and a command-line tool that uses this library.

%package bin
Summary: bin components for the pandoc package.
Group: Binaries
Requires: pandoc-license = %{version}-%{release}

%description bin
bin components for the pandoc package.


%package license
Summary: license components for the pandoc package.
Group: Default

%description license
license components for the pandoc package.


%package man
Summary: man components for the pandoc package.
Group: Default

%description man
man components for the pandoc package.


%prep
%setup -q -n pandoc-2.17.1.1
cd %{_builddir}
tar xf %{_sourcedir}/sources-2.17.1.1.tar.gz
cd %{_builddir}/pandoc-2.17.1.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1643667294
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
make  %{?_smp_mflags}  || :


%install
export SOURCE_DATE_EPOCH=1643667294
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pandoc
cp %{_builddir}/pandoc-2.17.1.1/COPYING.md %{buildroot}/usr/share/package-licenses/pandoc/049f06824254a57ed970100c46dd7d580e67d0aa
cp %{_builddir}/pandoc-2.17.1.1/COPYRIGHT %{buildroot}/usr/share/package-licenses/pandoc/cdd21a3abb40a731f6120ed35b9207097c83950d
:
## install_append content
mkdir -p %{buildroot}/usr
cp -r bin %{buildroot}/usr/
cp -r share %{buildroot}/usr/
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pandoc

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pandoc/049f06824254a57ed970100c46dd7d580e67d0aa
/usr/share/package-licenses/pandoc/cdd21a3abb40a731f6120ed35b9207097c83950d

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/pandoc.1.gz
